package database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Persie
 */
public class details extends javax.swing.JFrame {

    /**
     * Creates new form details
     */
    public details() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        e1 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        e4 = new javax.swing.JTextField();
        e11 = new javax.swing.JTextField();
        e13 = new javax.swing.JTextField();
        e12 = new javax.swing.JTextField();
        e14 = new javax.swing.JTextField();
        e15 = new javax.swing.JTextField();
        e16 = new javax.swing.JTextField();
        e17 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        e8 = new javax.swing.JComboBox<>();
        e9 = new javax.swing.JComboBox<>();
        e10 = new javax.swing.JComboBox<>();
        e5 = new javax.swing.JComboBox<>();
        e6 = new javax.swing.JComboBox<>();
        e7 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        e18 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        e19 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 130, 140, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("E-mail");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 240, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Phone No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 190, 130, 29);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Class");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 290, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Section");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 290, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Occupation");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(450, 370, 140, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 90, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Mother's Name");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(140, 410, 137, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("phone no.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(740, 360, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Occupation");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 410, 103, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("phone no.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(740, 400, 91, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Date Of Birth");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(760, 160, 170, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Address");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(131, 460, 130, 29);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Father's Name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(140, 370, 131, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel15.setText("Student's Profile");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(350, 20, 320, 40);

        e2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        jPanel1.add(e2);
        e2.setBounds(360, 130, 270, 40);

        e1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        jPanel1.add(e1);
        e1.setBounds(360, 80, 270, 40);

        e3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e3.setText("+91 ");
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        jPanel1.add(e3);
        e3.setBounds(360, 180, 270, 40);

        e4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(e4);
        e4.setBounds(360, 230, 320, 40);

        e11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e11ActionPerformed(evt);
            }
        });
        jPanel1.add(e11);
        e11.setBounds(290, 362, 150, 30);

        e13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e13.setText("+91 ");
        e13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e13ActionPerformed(evt);
            }
        });
        jPanel1.add(e13);
        e13.setBounds(840, 362, 160, 30);

        e12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e12ActionPerformed(evt);
            }
        });
        jPanel1.add(e12);
        e12.setBounds(560, 360, 170, 30);

        e14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e14ActionPerformed(evt);
            }
        });
        jPanel1.add(e14);
        e14.setBounds(290, 403, 150, 30);

        e15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e15ActionPerformed(evt);
            }
        });
        jPanel1.add(e15);
        e15.setBounds(560, 402, 170, 30);

        e16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e16.setText("+91 ");
        e16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e16ActionPerformed(evt);
            }
        });
        jPanel1.add(e16);
        e16.setBounds(840, 402, 160, 30);

        e17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e17ActionPerformed(evt);
            }
        });
        jPanel1.add(e17);
        e17.setBounds(290, 450, 670, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(590, 580, 180, 60);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 51, 51));
        jButton2.setText("HOME");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(850, 30, 160, 60);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Stream");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(150, 280, 100, 40);

        e8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        e8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course", "Medical", "Non-Medical", "Commerce", "Arts", "Super-Medical" }));
        jPanel1.add(e8);
        e8.setBounds(250, 292, 110, 30);

        e9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        e9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "LKG", "UKG", "Ist", "IInd", "IIIrd", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" }));
        jPanel1.add(e9);
        e9.setBounds(460, 292, 90, 30);

        e10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A", "B", "C", "D" }));
        e10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e10ActionPerformed(evt);
            }
        });
        jPanel1.add(e10);
        e10.setBounds(700, 292, 80, 30);

        e5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        e5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        e5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e5ActionPerformed(evt);
            }
        });
        jPanel1.add(e5);
        e5.setBounds(720, 210, 60, 22);

        e6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        e6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(e6);
        e6.setBounds(800, 210, 90, 22);

        e7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        e7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1991", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(e7);
        e7.setBounds(899, 210, 70, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Session");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(130, 510, 100, 40);

        e18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        e18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e18ActionPerformed(evt);
            }
        });
        jPanel1.add(e18);
        e18.setBounds(290, 510, 150, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("+ADD+Profile+");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(860, 0, 160, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Assignined Roll No.");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(498, 520, 190, 22);

        e19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(e19);
        e19.setBounds(700, 512, 190, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/detail.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(-60, 0, 1160, 770);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e2ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e3ActionPerformed

    private void e12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e12ActionPerformed

    private void e13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e13ActionPerformed

    private void e11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e11ActionPerformed

    private void e16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e16ActionPerformed

    private void e15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e15ActionPerformed

    private void e14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e14ActionPerformed

    private void e17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e17ActionPerformed

    private void e5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e5ActionPerformed

    private void e18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e18ActionPerformed

    private void e10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e10ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_e1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection con=null;
Statement st=null;
try
{
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kid","root","1234");
    st=con.createStatement();
    String sql=("insert into infop(first,last,phone,email,day,month,year,stream,class,section,fat,occ,pho1,mot,occ2,pho2,address,session,rollno)"+"values('"+e1.getText() +"','"+e2.getText() +"','"+e3.getText() +"','"+e4.getText() +"','"+e5.getSelectedItem() +"','"+e6.getSelectedItem() +"','"+e7.getSelectedItem() +"','"+e8.getSelectedItem() +"','"+e9.getSelectedItem() +"','"+e10.getSelectedItem() +"','"+e11.getText() +"','"+e12.getText() +"','"+e13.getText() +"','"+e14.getText() +"','"+e15.getText() +"','"+e16.getText() +"','"+e17.getText() +"','"+e18.getText() +"','"+e19.getText()+"')" );
    st.executeUpdate(sql);
     JOptionPane.showMessageDialog(null," added successfully");
      this.setVisible(false);
}
catch(Exception e)
{
    e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new add().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField e1;
    private javax.swing.JComboBox<String> e10;
    private javax.swing.JTextField e11;
    private javax.swing.JTextField e12;
    private javax.swing.JTextField e13;
    private javax.swing.JTextField e14;
    private javax.swing.JTextField e15;
    private javax.swing.JTextField e16;
    private javax.swing.JTextField e17;
    private javax.swing.JTextField e18;
    private javax.swing.JTextField e19;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField e4;
    private javax.swing.JComboBox<String> e5;
    private javax.swing.JComboBox<String> e6;
    private javax.swing.JComboBox<String> e7;
    private javax.swing.JComboBox<String> e8;
    private javax.swing.JComboBox<String> e9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
