package database;

import static java.lang.reflect.Array.set;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Persie
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        r2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        r3 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        r5 = new javax.swing.JTextField();
        r6 = new javax.swing.JTextField();
        r8 = new javax.swing.JTextField();
        r19 = new javax.swing.JTextField();
        r9 = new javax.swing.JTextField();
        r7 = new javax.swing.JTextField();
        r10 = new javax.swing.JTextField();
        r11 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        r12 = new javax.swing.JTextField();
        r16 = new javax.swing.JComboBox<>();
        r17 = new javax.swing.JComboBox<>();
        r18 = new javax.swing.JComboBox<>();
        r13 = new javax.swing.JComboBox<>();
        r14 = new javax.swing.JComboBox<>();
        r15 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Session");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(610, 460, 80, 30);

        jLabel2.setFont(new java.awt.Font("Stencil", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("UPDATE corner");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 310, 70);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("First Name");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(70, 90, 110, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Father's Name");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 250, 140, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Last Name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 130, 100, 30);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel15.setText("Address");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(620, 320, 110, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Phone No.");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(70, 170, 100, 30);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Mother's Name");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 330, 140, 30);

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel19.setText("Roll No.");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(560, 20, 150, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("E-Mail");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(70, 210, 90, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Occupation");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(240, 250, 110, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Occupation");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(240, 330, 110, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Phone No.");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(400, 330, 100, 30);

        r2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });
        jPanel1.add(r2);
        r2.setBounds(250, 90, 220, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Phone No.");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(400, 250, 140, 30);

        r3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r3);
        r3.setBounds(250, 130, 220, 30);

        r4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r4);
        r4.setBounds(250, 170, 220, 30);

        r5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r5);
        r5.setBounds(250, 210, 330, 30);

        r6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r6ActionPerformed(evt);
            }
        });
        jPanel1.add(r6);
        r6.setBounds(30, 280, 170, 30);

        r8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r8);
        r8.setBounds(400, 280, 180, 30);

        r19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r19);
        r19.setBounds(690, 460, 140, 30);

        r9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r9);
        r9.setBounds(30, 370, 170, 30);

        r7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r7ActionPerformed(evt);
            }
        });
        jPanel1.add(r7);
        r7.setBounds(230, 280, 150, 30);

        r10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r10);
        r10.setBounds(230, 370, 150, 30);

        r11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(r11);
        r11.setBounds(400, 370, 180, 30);

        r1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });
        jPanel1.add(r1);
        r1.setBounds(700, 10, 290, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Section");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 460, 90, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Class");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(240, 460, 90, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Date of Birth");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 410, 120, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Stream");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 460, 90, 40);

        r12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(r12);
        r12.setBounds(620, 360, 350, 40);

        r16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Course", "Medical", "Non-Medical", "Commerce", "Arts", "Super-Medical" }));
        jPanel1.add(r16);
        r16.setBounds(120, 460, 100, 30);

        r17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "LKG", "UKG", "Ist", "IInd", "IIIrd", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII" }));
        jPanel1.add(r17);
        r17.setBounds(300, 460, 90, 30);

        r18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A", "B", "C", "D" }));
        r18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r18ActionPerformed(evt);
            }
        });
        jPanel1.add(r18);
        r18.setBounds(480, 460, 80, 30);

        r13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        r13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r13ActionPerformed(evt);
            }
        });
        jPanel1.add(r13);
        r13.setBounds(190, 420, 60, 22);

        r14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jPanel1.add(r14);
        r14.setBounds(280, 420, 90, 22);

        r15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        r15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1991", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019" }));
        jPanel1.add(r15);
        r15.setBounds(390, 420, 70, 22);

        jButton1.setFont(new java.awt.Font("Wide Latin", 3, 36)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 153), new java.awt.Color(255, 0, 204)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 580, 320, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 580, 130, 50);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(990, 20, 30, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 0, 102), new java.awt.Color(255, 0, 0), new java.awt.Color(255, 0, 102), new java.awt.Color(255, 51, 51)));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-270, -810, 1630, 1910);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r7ActionPerformed

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r1ActionPerformed

    private void r18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r18ActionPerformed

    private void r13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Connection con=null;
Statement st=null;
        int flag = 0;
        try 
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kid","root","1234");
            st=con.createStatement();
            String sql="update infop set first='"+r2.getText()+"',last='"+r3.getText()+"',phone='"+r4.getText()+"',email='"+r5.getText()+"',fat='"+r6.getText()+"',occ='"+r7.getText()+"',pho1='"+r8.getText()+"',mot='"+r9.getText()+"',occ2='"+r10.getText()+"',pho2='"+r11.getText()+"',address='"+r12.getText()+"',day='"+r13.getSelectedItem()+"',month='"+r14.getSelectedItem()+"',year='"+r15.getSelectedItem()+"',stream='"+r16.getSelectedItem()+"',class='"+r17.getSelectedItem()+"',section='"+r18.getSelectedItem()+"',session='"+r19.getText()+"'"+"where rollno="+r1.getText();
       st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null," Updated successfully");
         this.setVisible(false);
         new add().setVisible(true);    
         
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
       // new add().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Connection con=null;
Statement st=null;
        int flag = 0;
        try 
        {
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kid","root","1234");
            st=con.createStatement();
            String sql="select * from infop where rollno="+r1.getText();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                r2.setText(rs.getString(1));
                    r3.setText(rs.getString(2));
                        r4.setText(rs.getString(3));
                            r5.setText(rs.getString(4));
                                r6.setText(rs.getString(11));
                                    r7.setText(rs.getString(12));
                                        r8.setText(rs.getString(13));
                                            r9.setText(rs.getString(14));
                                                r10.setText(rs.getString(15));
                                                    r11.setText(rs.getString(16));
                                                        r12.setText(rs.getString(17));
                                                            r13.setSelectedItem(rs.getString(5));
                                                                r14.setSelectedItem(rs.getString(6));
                                                                    r15.setSelectedItem(rs.getString(7));
                                                                        r16.setSelectedItem(rs.getString(8));
                                                                            r17.setSelectedItem(rs.getString(9));
                                                                                r18.setSelectedItem(rs.getString(10));
                                                                                    r19.setText(rs.getString(18));
                            
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
// TODO add your handling code here:
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void r6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r6ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_r2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r10;
    private javax.swing.JTextField r11;
    private javax.swing.JTextField r12;
    private javax.swing.JComboBox<String> r13;
    private javax.swing.JComboBox<String> r14;
    private javax.swing.JComboBox<String> r15;
    private javax.swing.JComboBox<String> r16;
    private javax.swing.JComboBox<String> r17;
    private javax.swing.JComboBox<String> r18;
    private javax.swing.JTextField r19;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JTextField r6;
    private javax.swing.JTextField r7;
    private javax.swing.JTextField r8;
    private javax.swing.JTextField r9;
    // End of variables declaration//GEN-END:variables
}
